name: chat-widget-release

on:
  push:
    tags:
      - 'w-v*'
    paths:
      - 'chat-widget/**'

jobs: 
  build:
    runs-on: windows-2019
    steps:
      - name: Checking out for ${{ github.ref }}
        run: echo "simulate tag execution"
