name: chat-components-release

on:
  push:
    tags:
      - 'c-v*'
    paths:
      - 'chat-components/**'

jobs: 
  build:
    runs-on: windows-2019
    steps:
      - name: Checking out for ${{ github.ref }}
        run: echo "simulate tag execution components"
